export enum ErrorCodes {
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  INVALID_PRODUCT_ID = "INVALID_PRODUCT_ID",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
}